### ISSUE TITLE
[Suggestion] Config Option To Make The Crafter Use Parts

### ISSUE THREAD

**Issue by EmosewaGamer** [dalapo/FactoryTech#43]

**Comment by dalapo** [comment]
During development it actually did use parts, but that was tossed because of how crucial to automation it is (There's a reason it's listed under automation instead of machines).

Is there any particular reason why you want this?

**Comment by EmosewaGamer** [comment]
For the progression of my pack. I set FactoryTech as early-game-ish mod and the Crafter is simply too good. As things get better as the player progresses, I need the Crafter to be flawed in some way. Having it require a Gear, even if it's one per a stack of crafted items would do that.

**Comment by dalapo** [comment]
Man, remember when BuildCraft had instantaneous, free autocrafting? Those were the days...

Anyway, yeah, I can do that - the only issue I have with it is that making the crafter require parts would make for a somewhat cumbersome setup since it's only one part of a bigger assembly line. I can make it still free by default, though. I assume your pack will have better autocrafters later on?

**Comment by EmosewaGamer** [comment]
Yes
